# encoding: utf-8
"""
Webserver Config
----------------
Configuration file of the webserver,

--=- generated by flask-install: https://github.com/0x78f1935/flask-install -=--
"""
from .modules import ModulesConfig
from dotenv import load_dotenv
from os import getenv

load_dotenv()
connection_url = f'mysql+pymysql://{getenv("DB_USERNAME", "root")}:{getenv("DB_PASSWORD", "SuperSecretPass123")}@{getenv("DB_HOST", "127.0.0.1")}:{getenv("DB_PORT", "3888")}/{getenv("DB_SCHEMA", "retro")}'



class Configuration(ModulesConfig):
    """The core of the webserver (backend) itself"""
    # - Webserver Configuration
    PROJECT_NAME = 'Retro'
    SECRET_KEY = 'yW41SgK5mtrRVp4BY3-OC09saqRscx1G'

    # - Flask Smorest (API)
    API_TITLE = 'Retro-API'
    API_VERSION = 'v1'
    API_SPEC_OPTIONS = {'x-internal-id': '2'}
    OPENAPI_VERSION = '3.0.2'
    OPENAPI_JSON_PATH = 'api-spec.json'
    OPENAPI_URL_PREFIX = '/'
    OPENAPI_UI = ['redoc', 'rapidoc', 'swagger']

    OPENAPI_SWAGGER_UI_PATH = '/swagger-ui'
    OPENAPI_SWAGGER_UI_URL = 'https://cdn.jsdelivr.net/npm/swagger-ui-dist/'

    OPENAPI_REDOC_PATH = '/docs'
    OPENAPI_REDOC_URL = 'https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js'

    OPENAPI_RAPIDOC_PATH = '/devs'
    OPENAPI_RAPIDOC_URL = 'https://unpkg.com/rapidoc/dist/rapidoc-min.js'

    # - Database
    DATABASE_TYPE = 'mysql'
    SQLALCHEMY_DATABASE_URI = connection_url
    SQLALCHEMY_TRACK_MODIFICATIONS = True

    # - JWT
    JWT_EXPIRE_IN_MINUTES = 10
    
    # - Retro Hotel
    STARTING_CREDITS = 2500
    STARTING_PIXELS=500
    STARTING_POINTS=10
    
    # - Emulator
    EMULATOR_HOST = getenv("EMULATOR_HOST", "http://127.0.0.1:81")

    # - Modules
    def __init__(self, *args, **kwargs) -> None:
        ModulesConfig.__init__(self)
