# encoding: utf-8
"""
Webserver Modules
-----------------
Within this class endpoint folders can be enabled, added, removed or disabled by removing the tuple from
ModulesConfig.ENABLED_MODULES. The tuple contains two values. The first value (str) is the prefix of the endpoint. The
second value (str) is the name of the folder containing endpoint code. The folder has to be present in the
backend/endpoints folder.

Note: v0 is a reserved endpoint prefix for flask-install which is used for mounting the frontend (vue) when initialized.

--=- generated by flask-install: https://github.com/0x78f1935/flask-install -=--
"""


class ModulesConfig(object):
    def __init__(self):
        """Configures enabled endpoints.

        Based on (version/prefix, extension/folder_name)
        """
        self.ENABLED_MODULES = [
            ("v0", "frontend"),
            ("v1", "users"),
            ("v1", "test"),
        ]
