version: '3.9'
services:
  cache:
    image: redis:alpine3.17
    container_name: retro-cache
    hostname: retro-cache
    restart: always
    networks:
      - retro_network
    ports:
      - $REDIS_PORT:6379
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./docker/volumes/redis:/data

networks:
  retro_network:
    driver: bridge
