# encoding: utf-8
"""
Webserver
---------
Entry point of the webserver, This file should be used in order to start the application.

--=- generated by flask-install: https://github.com/0x78f1935/flask-install -=--
"""
from backend import Webserver
from backend.cli import register


def create_server() -> object:
    """
    This method is used to create a new server instance

    Returns:
        object: Application Webserver
    """
    server = Webserver()
    register(server)
    return server


app = create_server()


@app.shell_context_processor
def make_shell_context():
    """Register quick access Flask Shell with variables pre-initialized"""
    return {
        'app': app
    }
