# encoding: utf-8
"""
Webserver CLI
-------------
Open a terminal in the root directory of this project.
Make sure to activate your virtualenvironment and set FLASK_APP to `webserver.py` in your environment variables.

Windows:
```
set FLASK_APP=webserver.py
```

Unix
```
export FLASK_APP=webserver.py
```

With the command `flask` you can discover all the available webserver commands.

--=- generated by flask-install: https://github.com/0x78f1935/flask-install -=--
"""


def register(app) -> None:
    @app.cli.group()
    def example():
        """Example CLI group"""
        pass

    @example.command()
    def hello():
        """Example CLI command"""
        print("Hello World!")
