# encoding: utf-8
"""
Webserver Extensions
--------------------
This file loads global available extensions of third/private/custome code

--=- generated by flask-install: https://github.com/0x78f1935/flask-install -=--
"""
from flask_smorest import Api  # noqa: E402
api = Api()

from flask_sqlalchemy import SQLAlchemy  # noqa: E402
db = SQLAlchemy()

from flask_migrate import Migrate  # noqa: E402

from flask_bcrypt import Bcrypt  # noqa: E402
bcrypt = Bcrypt()

from backend.extensions.loginmanager import LoginManager  # noqa: E402
loginmanager = LoginManager()


def init_app(app) -> None:
    """
    Application extensions initialiation method -> Lazy load
    """
    for extensions in (
        api,
        db,
        bcrypt,
        loginmanager
    ):
        extensions.init_app(app)
    Migrate(app, db)
