# encoding: utf-8
"""
Resources: Frontend
-------------------
This simply serves the frontend application

--=- generated by flask-install: https://github.com/0x78f1935/flask-install -=--
"""
from flask import render_template
from flask.views import MethodView

from flask_smorest import Blueprint
blp = Blueprint('Frontend Application', 'Frontend Application', description='Frontend Application', url_prefix='/')


class FrontendApplication(MethodView):
    @blp.route('/', methods=['GET'])
    def frontend(*args, **kwargs):
        """
        Frontend Application

        This is our main page where we serve our frontend application
        """
        return render_template('application.jinja2')

    @blp.route('/client', methods=['GET'])
    def frontend(*args, **kwargs):
        """
        Client Application

        This is our main page where we serve our frontend application
        """
        return render_template('client.jinja2')
