"""empty message

Revision ID: 8caa7460d418
Revises: 40a0cdf27560
Create Date: 2022-11-30 23:13:04.759803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8caa7460d418'
down_revision = '40a0cdf27560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_authentication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_authentication', schema=None) as batch_op:
        batch_op.drop_column('scope')
    # ### end Alembic commands ###
