"""empty message

Revision ID: fe68d5b6be2e
Revises: 8caa7460d418
Create Date: 2022-12-01 23:40:27.270972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe68d5b6be2e'
down_revision = '8caa7460d418'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('cms_authentication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_id', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_authentication', schema=None) as batch_op:
        batch_op.drop_column('enc_id')
